# requires files generated by cell_lines and strains
devtools::load_all()
python = new.env()
reticulate::source_python(system.file('gpt.py',package= 'GPTests'),python)
gpt = python$gpt_query()

gpt = python$gpt_query(prompt = readLines('analysis/delegator/prompt') %>% 
                           paste(collapse = '\n'),
                       response_format = delegator_output)

cell_line_list = readRDS('data-raw/cell_line_data/cell_line_list.rds')
strain_list = readRDS('data-raw/strain_data/strain_list.rds')


strains = readRDS('data-raw/strain_data/main_frame.rds')
cell_lines = readRDS('data-raw/cell_line_data/main_frame.rds')


input_names = c(strains$shortName,cell_lines$shortName) %>% unique

dir.create('data-raw/delegator_data')
all_inputs = input_names %>% pbapply::pblapply(create_input)
names(all_inputs) = input_names
saveRDS(all_inputs,'data-raw/delegator_data/delegator_inputs.rds')
inputs = create_input_batches(all_inputs )
dir.create('data-raw/delegator_data/delegator_inputs/')
for (inp in names(inputs)){
    writeLines(jsonlite::toJSON(inputs[[inp]],pretty = TRUE),
               con = glue::glue('data-raw/delegator_data/delegator_inputs/{inp}.json'))
}
